version: "3.9"

services:
  api:
    image: dev/finportman-api
    # restart: always
    environment:
      - KEYS_ALPHAVANTAGE=${KEYS_ALPHAVANTAGE}
      - NEWS_API_KEY=${NEWS_API_KEY}
  app:
    depends_on:
      - api
    image: dev/finportman-app
    # restart: always
  proxy:
    depends_on:
      - app
    image: nginx:alpine
    # restart: always
    ports:
      - ${PORT}:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
